### PR TITLE
feat: can read snippet body from file

### PR DESCRIPTION
**Pull request by mg979**
Addresses #65.

If you like this kind of approach, that is. It can make easier writing long templates.

### CODE REVIEW

**Comment by hrsh7th** [comment]
In the past of time, the snippet file was locked in to some snippet engine but Microsoft gives us the standard snippet format in the LSP spec. I respect this work.

So in my personal opinion, I hope to avoid being created snippet file that works only on vsnip.

I know, I wad added $VIM variable.
It work only in vim but it realized by the way of keeping consistency to the LSP spec.


However, this PR's approach will break the VSCode comoatibility but LSP spec compatibility does not...Hm...

**Comment by mg979** [comment]
The extra key `from_file` is read when snippet is formatted, then discarded, because `snippet.body` becomes that file. So the snippet format doesn't change, when the snippet is stored. Yes it's vim specific, but you can't use the plugin with VSCode anyway... 

Anyway it's just an idea, if you don't like it it's ok.

**Comment by hrsh7th** [comment]
Sorry, I want to take a time to consider more carefully, I understand,  anyway we should solve the problem that is creating snippet too tedious.

This approach is one of the way to solve it.

**Comment by mg979** [comment]
No problem. Actually one could have some kind of macros/custom commands that makes a `body` out of a file, to take care of this stuff, so it's not really needed.

**Comment by mg979** [comment]
By the way I can close this, I had a better idea.

**Pull request closed without merging**
