### PR TITLE
Expand nested snippet

### LINKED ISSUE #37: Snippet deactivated after nested completion
**Steps to reproduce:**
1. Download [akd](https://github.com/Shatur95/akd) (small project with few files, just for example)
2. Open `main.cpp`.
3. Add `#include <algorithm>`.
4. type `std::string test;`.
5. Try to pass it into `std::generate`. This function accept iterators. If I pass just `test` - snippet will not deactivated. But if I pass `test.begin()` iterator - snippet will be deactivated.

Tested with `asyncomplete` and `vim-lsp`.

**Video:**
[asciicast](https://asciinema.org/a/KTmuXv51AUMJnvrv3wmvTEzNm)

**vsnip configuration:**
```vim
let g:vsnip_snippet_dir = expand('~/.config/nvim/vsnip')
let g:vsnip_integ_config = {}
let g:vsnip_integ_config.auto_expand = v:true

imap <expr> <Tab> pumvisible() ? '<Down>' : vsnip#available(1) ? '<Plug>(vsnip-jump-next)' : '<Tab>'
smap <expr> <Tab> pumvisible() ? '<Down>' : vsnip#available(1) ? '<Plug>(vsnip-jump-next)' : '<Tab>'
imap <expr> <C-Tab> pumvisible() ? '<Up>' : '<Plug>(vsnip-jump-prev)'
smap <expr> <C-Tab> pumvisible() ? '<Up>' : '<Plug>(vsnip-jump-prev)'
```

### PR DESCRIPTION
**Pull request by hrsh7th**
Fix #37 

This implementation is useful.
But we should refactor and improve it.

1. buffer text management is ugly
2. backward jump can be improved (should replace current tabstop).

### CODE REVIEW

**Comment by hrsh7th** [comment]
When expanding nested snippet in the not follower snippet, the snippet is broken.
I think it is not a critical bug... but...

**Comment by hrsh7th** [comment]
nested-snippet-expansion

BTW, animated gif is very heavy... more best solution, I want.

**Comment by hrsh7th** [comment]
test
docs

**Comment by Shatur95** [comment]
You have very cool auto-completion for vim, what kind of plugin are you using?

**Comment by Shatur95** [comment]
What auto-completion plugin are you using? It looks very cool :)

**Comment by prabirshrestha** [comment]
Also another interesting approach could be using textprops but not compatible with older vim.

https://reddit.com/r/vim/comments/fh4z2y/axelf4vimsnippsnappsnutandthelegendcontinues/

**Comment by hrsh7th** [comment]
The text-properties approach is makes lightweight behaivior maybe.

But I think it is not fit to AST approach (vsnip is this).

I thinking now vsnip should support listener_add instead of text-properties.

**Comment by Shatur95** [comment]
I found a bug with lambda expressions:
[asciicast](https://asciinema.org/a/EHve76viAlqP3S1bIDHx1XOJG)

**Comment by hrsh7th** [comment]
Hm... it seems broken but I don't know the reason.

Could you explain more simple repro steps?

**Comment by Shatur95** [comment]
Okay :)
1. Create `main.cpp` file.
2. Copy this code:
```cpp
#include <algorithm>
#include <vector>

int main()
{
    std::vector<double> test;
}
```
3. Try to to type inside the function:
```cpp
std::find_if(test.begin(), test.end(), [](){
    return true;
});
```

I using `clangd` for autocompletion. It looks like it happening only in nested snippets because the following construction is works:
```cpp
auto test = []() {
    return 0;
}
```

**Comment by hrsh7th** [comment]
Sorry, I don't have clangd environment...

I try to check with `vim-language-server`.

```
  "test3": {
    "prefix": ["test3"],
    "body": [
      "[]() {$1}"
    ]
  },
```

I've added this sample snippet to vim.

Kapture 2020-03-16 at 11 38 50

**Comment by hrsh7th** [comment]
But I found the other problem in `json-languageserver`'s snippet maybe.

**Comment by hrsh7th** [comment]
Probably the problem was solved.

@Shatur95 Could you test with latest `merge` branch?

**Comment by Shatur95** [comment]
Yes, it fixed the issue, thank you!

I have not related question. What do you use for floating previews and completion? I have `vim-language-server` and using [float-preview](https://github.com/ncm2/float-preview.nvim) for previews. But it not shows preview for such functions (the same with default previews):
изображение
And shows very bad formatted previews for arguments:
изображение

**Comment by hrsh7th** [comment]
@Shatur95 

1. floating-docs
This is `vim-lamp`'s feature.

2. hover highlighting
You can install `tpope/vim-markdown` and set `let g:markdown_fenced_languages = ['help']`

**Comment by Shatur95** [comment]
Thank you a lot for the implementation and help!

**Pull request merged**
