### PR TITLE
removed friendly-snippets supported languages list

### PR DESCRIPTION
**Pull request by RaafatTurki**

### CODE REVIEW

**Comment by gegoune** [comment]
Instead of making it longer I would actually remove that list completely. Interested users can check out friendly-snippets repo for more info. Don't think there is a need to make such a long list right at the top of README, even before actually plugin's usage is shown.

I would actually move Related Repository section to the very end. Maybe before Development.

**Comment by RaafatTurki** [comment]
I'd suggest the same, ill leave such judgment to the ones in charge.

**Comment by hrsh7th** [comment]
Thank you. I think the full list can be removed for now because the `friendly-snippets` became to be the most popular snippets collection in the neovim community.

**Comment by RaafatTurki** [comment]
list is gone now :D

**Comment by hrsh7th** [comment]
Thank you! (Sorry for the delayed reply!

**Pull request merged**
