### PR TITLE
Add backward jump mapping

### PR DESCRIPTION
**Pull request by hrsh7th**

### CODE REVIEW

**Comment by pwntester** [comment]
Thanks for implementing it, I had some trouble with muliple choice placeholders.

Does it work for you with a snippet such as?

```
{
  "foo": {
    "prefix": "foo",
    "body": [
        "FOO ${1:test}",
        "BAZ ${3|baz,lol,luz|}",
        "BAR ${2:bar}",
        "LM ${TM_CURRENT_LINE}"
    ],
    "description": "FOO TEST."
  }
}
```

In my case (using the following mappings:

```
imap <expr> <Tab> vsnip#available() ? '<Plug>(vsnip-expand-or-jump)' : '<Tab>'
smap <expr> <Tab> vsnip#available() ? '<Plug>(vsnip-expand-or-jump)' : '<Tab>'
imap <expr> <S-Tab> vsnip#available() ? '<Plug>(vsnip-jump-prev)' : '<S-Tab>'
smap <expr> <S-Tab> vsnip#available() ? '<Plug>(vsnip-jump-prev)' : '<S-Tab>'
```
)

jumping forward skips the BAZ placeholder so it jumps from FOO to BAR
When on BAR, jumping backwards also skips BAZ so it jumps back to FOO

**Comment by hrsh7th** [comment]
It is my mistake. I understood the reason.
But it will need breaking change to solve it...
Anyway, fix it.

**Comment by hrsh7th** [comment]
@pwntester I've fixed the issue. Please check it if you have time.

It has breaking change, please check https://github.com/hrsh7th/vim-vsnip/blob/master/.vimrc before check.

**Comment by pwntester** [comment]
Thanks,

Tried with:

```
imap <expr> <Tab> vsnip#available(1) ? '<Plug>(vsnip-expand-or-jump)' : '<Tab>'
smap <expr> <Tab> vsnip#available(1) ? '<Plug>(vsnip-expand-or-jump)' : '<Tab>'
imap <expr> <S-Tab> vsnip#available(-1) ? '<Plug>(vsnip-jump-prev)' : '<S-Tab>'
smap <expr> <S-Tab> vsnip#available(-1) ? '<Plug>(vsnip-jump-prev)' : '<S-Tab>'
```

and got the same problems. Is that a correct config?

**Comment by hrsh7th** [comment]
Ah, Sorry. The jump sequence is right.

Jump sequence is using tabstop order so the case should jump `FOO -> BAR -> BAZ`.

**Comment by pwntester** [comment]
oh my bad, I had incorrect order in placeholders. Now its working as expected, thanks!

The only odd thing is that first time that I get to the multi-option placeholder (2), the menu is displayed and immediatly closed. If then I move to 3rd placeholder and then back to the 2nd one, the menu is displayed and it stays.

Do you get the same behaviour?

**Comment by hrsh7th** [comment]
You use auto-completion engine, so pum is overwitten by it.
I want to fix it but it's difficult...

**Comment by hrsh7th** [comment]
the choice problemcis not related this PR.
So the PR ok to merge, I think.

**Pull request merged**
