### PR TITLE
fix: VsnipOpen evaluates all possible directories

### PR DESCRIPTION
**Pull request by mg979**

### CODE REVIEW

**Comment by hrsh7th** [comment]
The purpose of `g:vsnip_snippet_dirs` is add the ability to provide the snippet as `vim-plugin`.

That means is the snippet under `g:vsnip_snippet_dirs` does not intent to modify by the user.

(I think if user modify it, user will meet the conflict via plugin-managers)


However, Currently, `g:vsnip_snippet_dirs` didn't use by any of the vsnip users.
Do you using it?

**Comment by mg979** [comment]
> Do you using it?

No. I didn't understand the purpose of `g:vsnip_snippet_dirs` (and I still don't understand the need for `b:vsnip_snippet_dir` and `b:vsnip_snippet_dirs`).

I understand now, but `b:vsnip_snippet_dir` is still unaccessible by the open command, so it's basically useless.

**Comment by hrsh7th** [comment]
Anyway, Thank you very much for your contributions.

I try to explain the purpose of `g:vsnip_snippet_dirs` by example repo (https://github.com/hrsh7th/vsnip-snippet-plugin-demo).

The `g:vsnip_snippet_dirs` has been available since the beginning of the vsnip project.
I think now, it may be an unneeded feature...

**Comment by mg979** [comment]
`g:vsnip_snippet_dirs` may be needed for plugins as you say... I just didn't understand the purpose.

But I think the buffer variants (`b:g:vsnip_snippet_dir` and `b:g:vsnip_snippet_dirs`) maybe are not needed (I don;t know why one would want to use them). Anyway `g:vsnip_snippet_dir` is not accessible by `VsnipOpen` right now, it is ignored, so it's uselsess right now.

**Comment by hrsh7th** [comment]
Right, we should use `b:vsnip_snippet_dir` at the `VsnipOpen` maybe.

I don't know the needs to `b:vsnip_sippet_dirs` too (it came from PR but I think it would be ok to have)

**Comment by mg979** [comment]
Yes, but it becomes a bit complicated. For example

- if I want to edit a snippet, what file should it open if both are valid?
- if I use a command that edits a snippet, how would it know where the original snippet was?

For example the `VsnipEditSnippet` from the other PR lets you choose a path if more than one snippet file is found, then it edits the snippet from that file,, but then VsnipOpen can't know which file was that.

**Comment by mg979** [comment]
If you want to keep buffer local variables then maybe you can do:

- `VsnipOpen` prefers `b:vsnip_snippet_dir` when opening snippet file
- `VsnipOpen [file]` opens a specific file

**Comment by hrsh7th** [comment]
Surely, probably we should show all of the possible snippets with paths?

```
* /path/to/b:vsnip_snippet_dir
  1. javascript
  2. tsx
* /path/to/g:vsnip_snippet_dir
  3. javascript
  4. tsx
```

**Comment by mg979** [comment]
If it's not too difficult to write that, otherwise just preferring the buffer local path would be easier.

**Comment by hrsh7th** [comment]
I think we should refactor as the below.

1. separate `user_snippet.vim` to `user_snippet.vim` and `plugin_snippet.vim`.
2. Use `user_snippet.vim`'s API in the VsnipOpen command.

I will try it later.

**Comment by mg979** [comment]
Sorry, I made some mess.

> VsnipOpen [file] opens a specific file

That was useless.

The only thing that remains is that remains is that `b:vsnip_snippet_dir` is ignored, if you want to support that in `VsnipOpen`.
Sorry again for the confusion.

**Comment by hrsh7th** [comment]
No problem. Your contribution is helpful to me.

Yes, `b:vsnip_snippet_dir` seems ignored now, I will tackle it.

**Pull request closed without merging**
