### PR TITLE
feat: VsnipEditSnippet

### PR DESCRIPTION
**Pull request by mg979**
Edit a snippet in a temporary buffer, then update source snippet file.

***For evaluation only, not for merging.***

I'm using `system python` to pretty print the json file, and it's required for the command. That is, a system python installation is required. There may be other tools to de-minify a json file, I don't know.

### CODE REVIEW

**Comment by mg979** [comment]
Then, if you don't want to include this feature, since it requires a pyton installation, I can make an extra plugin (but I'd need a function from this PR).

**Comment by hrsh7th** [comment]
I tried to use it.

I don't think it has reached the quality of being merged.
For example, I want to invoke `VsnipEditSnippet` on the `vim.json` but it will be listing the `json.json`'s snippets.

But I think we can make it more useful. The approach has the potential to enhance UX.
I'm starting consider it.

Anyway, feel free to create a separate plugin.
What API do I need to expose to create a separate plugin?

**Comment by mg979** [comment]
> For example, I want to invoke VsnipEditSnippet on the vim.json but it will be listing the json.json's snippets.

I didn't consider this. But one could want to have snippets for `json` files, so I don't think it's wrong. Insteaad, there could be buffer mapping set by `VsnipOpen`:

    <CR>    VSnipEditSnippet [snippet] at cursor position
    <F1>    list snippets and select one for editing

> What API do I need to expose to create a separate plugin?

This
https://github.com/hrsh7th/vim-vsnip/blob/2ac88dd6211084ed54a32cdbf8ff0d05972a7526/autoload/vsnip/source/user_snippet.vim#L57-L61

**Comment by mg979** [comment]
For now I'm closing both PRs, instead I make a PR for the functions needed for an external plugin. Then if you want to include the functionality (maybe in `vsnip-integ` if you prefer) I can make a new PR.

**Comment by hrsh7th** [comment]
Thank you for your work!
It makes an insight into me.

**Comment by mg979** [comment]
I made a plugin for this here

https://github.com/mg979/vim-vsnip-edit

Then you can think about it.

**Pull request closed without merging**
