### PR TITLE
Support expanding snippets from select mode

### LINKED ISSUE #49: Visual mode snippet expansion
I'm currently migrating from UltiSnips.
It is possible to use `$VISUAL` there which is the text which was selected when triggering the snippet:
You select text, type an expansion keystroke, type the snippet and then again the keystroke (in insert)
Then the snippet is expanded and every appearance of `$VISUAL` is replaced. Not literally - using `VISUAL` as a placeholder was supported as well.

Reading the docs from Microsoft `$TM_SELECTED_TEXT` should be the equivalent. But I haven't got it to work yet.
Is this supported yet?

### PR DESCRIPTION
**Pull request by jandamm**
This PR allows to add a mapping in select mode which will expand a snippet if one exists.

This Closes #49 `b)`

Example:
```json
{
  "Augroup": {
    "prefix": ["aug"],
    "body": [
      "augroup my_augroup",
      "\tau!",
      "\t${1:auc}",
      "augroup END"
    ],
    "description": "Augroup wrapper."
  },
  "Autocmd": {
    "prefix": ["auc"],
    "body": [ "autocmd ${1:autocmd ${2:VimEnter} ${3:*}} $0" ],
    "description": "Function definition template."
  }
}
```
```vim
imap <expr> <C-j>   vsnip#available(1)  ? '<Plug>(vsnip-expand)'         : '<C-j>'
" Expand selected placeholder with <C-j>
smap <expr> <C-j>   vsnip#expandable()  ? '<Plug>(vsnip-expand)'         : '<C-j>'
```

Type `aug` and then press `<C-j>`. This will expand the `aug` snippet and jump to the first tabstop with `auc` in select mode.
Now press `<C-j>` again to expand the `auc` snippet.

### CODE REVIEW

**Comment by hrsh7th** [comment]
Thank you!
I will test and consider this feature.

**Comment by hrsh7th** [comment]
I've tested it works fine.
Could you add the document to doc/vsnip.txt?

**Comment by hrsh7th** [comment]
Sorry, It seems to have the problem when using the below snippet in go.

```json
{
  "struct": {
    "prefix": ["s", "struct"],
    "body": [
      "type $1 struct {",
      "\t${2:struct-prop}",
      "}"
    ]
  },
  "struct-prop": {
    "prefix": ["sp", "struct-prop"],
    "body": [
      "${1:key-name} ${2:type-name} ${3:`json:\"${4:$1}${5:,omitempty}\"`}$0"
    ]
  }
}
```

To repro,

1. Expand snippet `struct`
2. Jump to `struct-prop`
3. Expand in select-mode with `<C-j>`
4. Jumpt to `${4:$1}`
5. Edit placeholder
6. Jump to `${5:,omitempty}`
7. Wrong texts were selected

I think it has a potential bug of vsnip.
I will investigate it but it bit difficult...

BTW, this feature is useful, thank you for your PR!

**Comment by hrsh7th** [comment]
Sorry again!

The problem does not relate to this PR!

When you add the docs, I will merge it.

**Comment by jandamm** [comment]
Added the docs 👍

**Comment by hrsh7th** [comment]
Thank you!

**Pull request merged**
